import type { Metadata } from "next";
import { dark, shadesOfPurple} from '@clerk/themes';
import { ClerkProvider } from "@clerk/nextjs";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Uber App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider appearance={{
      baseTheme: shadesOfPurple
    }}>
      <html lang="en">
        <body className={outfit.className}>
          <Navbar />
          <div className="">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
